# Mirrors official helm-chart/values.yaml image structure
images:
  repository: us-central1-docker.pkg.dev/google-samples/microservices-demo
  tag: "v0.10.5"

replicaCount: 1

services:
  productCatalog: "productcatalogservice:3550"
  shipping: "shippingservice:50051"
  payment: "paymentservice:50051"
  email: "emailservice:5000"
  currency: "currencyservice:7000"
  cart: "cartservice:7070"
