apiVersion: v1
kind: ServiceAccount
metadata:
  name: productcatalogservice
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: currencyservice
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recommendationservice
  namespace: {{ .Release.Namespace }}
