apiVersion: v1
kind: ServiceAccount
metadata:
  name: emailservice
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paymentservice
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shippingservice
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
  namespace: {{ .Release.Namespace }}
