apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cartservice
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: online-boutique
spec:
  project: default
  source:
    repoURL: https://github.com/ashikMostofaTonmoy/app-of-apps-demo.git
    targetRevision: main
    path: charts/cartservice
  destination:
    server: https://kubernetes.default.svc
    namespace: onlineboutique
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
